### ISSUE TITLE
Debug Mode: Adding debug mode and its documentation

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-local-node#269]
### Description

`hedera debug $timestamp` cannot find the correct record file to parse.

### Steps to reproduce

run `hedera debug` with any valid timestmp

### Hedera network

other

### Version

latest

### Operating system

None
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-local-node/issues/475
- [ ] https://github.com/hashgraph/hedera-local-node/issues/476
- [ ] https://github.com/hashgraph/hedera-local-node/issues/477
- [ ] https://github.com/hashgraph/hedera-local-node/issues/480
```
