### ISSUE TITLE
Enhanced Local Node Experience

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#354]
### Problem

As a developer I'd like to have better local-node experience.

### Solution

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-local-node/issues/341
- [ ] https://github.com/hashgraph/hedera-local-node/issues/319
- [ ] https://github.com/hashgraph/hedera-local-node/issues/294
- [ ] https://github.com/hashgraph/hedera-local-node/issues/290
- [ ] https://github.com/hashgraph/hedera-local-node/issues/266
- [ ] https://github.com/hashgraph/hedera-local-node/issues/230
- [ ] https://github.com/hashgraph/hedera-local-node/issues/219
- [ ] https://github.com/hashgraph/hedera-local-node/issues/368
```

**Comment by Nana-EC** [comment]
Moving https://github.com/hashgraph/hedera-local-node/issues/295 out of the Epic and closing.
295 is likely an Epic on it's own and doesn't tightly map to the rest
