### ISSUE TITLE
Local Node Major Refactor

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#417]
After the completion of the local node refactor, there are still items that needs to be resolved, before it's complete for release.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-local-node/issues/418
- [ ] https://github.com/hashgraph/hedera-local-node/issues/444
- [ ] https://github.com/hashgraph/hedera-local-node/issues/435
- [ ] https://github.com/hashgraph/hedera-local-node/issues/308
- [ ] https://github.com/hashgraph/hedera-local-node/issues/269
- [ ] https://github.com/hashgraph/hedera-local-node/issues/436
- [ ] https://github.com/hashgraph/hedera-local-node/issues/441
- [ ] https://github.com/hashgraph/hedera-local-node/issues/433
- [ ] https://github.com/hashgraph/hedera-local-node/issues/411
- [ ] https://github.com/hashgraph/hedera-local-node/issues/403
- [ ] https://github.com/hashgraph/hedera-local-node/issues/437
- [ ] https://github.com/hashgraph/hedera-local-node/issues/434
- [ ] https://github.com/hashgraph/hedera-local-node/issues/440
- [ ] https://github.com/hashgraph/hedera-local-node/issues/317
- [ ] https://github.com/hashgraph/hedera-local-node/issues/438
```

**Comment by georgi-l95** [comment]
Needed issues before this version can replace current are:
- Add fallback for output.code 1 when starting docker
- Fix TUI
- Update README.md

**Comment by georgi-l95** [comment]
This major endeavour has been completed. Therefore closing this ticket.
