### ISSUE TITLE
Enhance Unit Test

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#494]
Currently we have completed structure and selected framework for unit tests.
Enhance the unit tests until we have sufficient coverage.

```[tasklist]
### Tasks
- [ ] Add tests to CI and integrate coverage report in the PRs
- [ ] Complete Coverage for Controller
- [ ] Complete Coverage for States
- [ ] Complete Coverage for Services
```
