### ISSUE TITLE
Add tests to CI and integrate coverage report in the PRs

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#495]
```[tasklist]
### Tasks
- [x] Add coverage support
- [ ] Run Unit Tests in CI
- [ ] Add coverage to CI
```
