### ISSUE TITLE
Complete Coverage for States

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-local-node#501]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-local-node/issues/502
- [ ] https://github.com/hashgraph/hedera-local-node/issues/519
- [ ] https://github.com/hashgraph/hedera-local-node/issues/511
- [ ] https://github.com/hashgraph/hedera-local-node/issues/524
- [ ] https://github.com/hashgraph/hedera-local-node/issues/521
- [ ] https://github.com/hashgraph/hedera-local-node/issues/515
- [ ] https://github.com/hashgraph/hedera-local-node/issues/513
- [ ] https://github.com/hashgraph/hedera-local-node/issues/510
- [ ] https://github.com/hashgraph/hedera-local-node/issues/507
```
