### ISSUE TITLE
Proposal: Sunset Terminal UI

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#793]
### Motivation
-----
Terminal User Interface was added as a way to showcase and make usage of the Local-Node to users. However it has not reached the level it needed to fulfill this role, due to being cluncky, unresponsive and laggy at times. It uses not supported anymore library and not many users use the feature. Another inconviniece is when most users want to just start the node, they'd need to add additional options in the cli command, especially when used in the CI.

### Proposal
-----
Sunset this feature with 1 month notice. Add a warning that it will be removed in 1 month time at the top of the user interface, as a way to flag to users.

### Task List
-----

```[EPIC: Sunset TUI]
### Tasks
- [ ] Add warning at the top on both detached and non-detached versions.
- [ ] Rework README.md
- [ ] Remove all TUI code and references.
```
