### ISSUE TITLE
Restore Local Node Functionality 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-local-node#823]
### Problem

Recently there seem to have been some regressions in the great local node experience that existed in Q2 and Q3.
We believe we can attribute this to docker updates and the multiple variations of user local directory and network configs that create variability and make troubleshooting difficult.

### Solution

Explore startup and execution flows to determine all the current issues faced by users and address the blocking items that are preventing a good first user experience.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-local-node/issues/820
- [ ] https://github.com/hashgraph/hedera-local-node/issues/822
- [ ] https://github.com/hashgraph/hedera-local-node/issues/818
- [ ] https://github.com/hashgraph/hedera-local-node/issues/819
- [ ] https://github.com/hashgraph/hedera-local-node/issues/821
- [ ] https://github.com/hashgraph/hedera-local-node/issues/828
- [ ] https://github.com/hashgraph/hedera-local-node/issues/849
- [ ] https://github.com/hashgraph/hedera-local-node/issues/862
- [ ] https://github.com/hashgraph/hedera-local-node/issues/863
- [ ] https://github.com/hashgraph/hedera-local-node/issues/800
- [ ] https://github.com/hashgraph/hedera-local-node/issues/438
```

**Comment by Nana-EC** [comment]
@natanasow assuming this is all set and README is up to date please close this ticket
